export const banks = [
  { id: '001', title: '(001) Banco Do Brasil S.A (BB)' },
  { id: '237', title: '(237) Bradesco S.A.' },
  { id: '335', title: '(335) Banco Digio S.A.' },
  { id: '260', title: '(260) Nu Pagamentos S.A (Nubank)' },
  { id: '290', title: '(290) PagSeguro Internet S.A.' },
  { id: '323', title: '(323) Mercado Pago – Conta Do Mercado Livre' },
  { id: '237', title: '(237) Next Bank (Mesmo Código Do Bradesco)' },
  { id: '637', title: '(637) Banco Sofisa S.A (Sofisa Direto)' },
  { id: '077', title: '(077) Banco Inter S.A.' },
  { id: '341', title: '(341) Itaú Unibanco S.A.' },
  { id: '104', title: '(104) Caixa Econômica Federal (CEF)' },
  { id: '033', title: '(033) Banco Santander Brasil S.A.' },
  { id: '212', title: '(212) Banco Original S.A.' },
  { id: '756', title: '(756) Bancoob – Banco Cooperativo Do Brasil S.A.' },
  { id: '655', title: '(655) Banco Votorantim S.A.' },
  { id: '655', title: '(655) Neon Pagamentos S.A (Memso Código Do Banco Votorantim)' },
  { id: '041', title: '(041) Banrisul – Banco Do Estado Do Rio Grande Do Sul S.A.' },
  { id: '389', title: '(389) Banco Mercantil Do Brasil S.A.' },
  { id: '422', title: '(422) Banco Safra S.A.' },
  { id: '070', title: '(070) BRB – Banco De Brasília S.A.' },
  { id: '136', title: '(136) Unicred Cooperativa LTDA' },
  { id: '741', title: '(741) Banco Ribeirão Preto S.A.' },
  { id: '739', title: '(739) Banco Cetelem S.A.' },
  { id: '743', title: '(743) Banco Semear S.A.' },
  { id: '100', title: '(100) Planner Corretora De Valores S.A.' },
  { id: '096', title: '(096) Banco B3 S.A.' },
  { id: '747', title: '(747) Banco Rabobank Internacional Do Brasil S.A.' },
  { id: '748', title: '(748) Banco Cooperativa Sicredi S.A.' },
  { id: '752', title: '(752) Banco BNP Paribas Brasil S.A.' },
  { id: '091', title: '(091) Unicred Central Rs' },
  { id: '399', title: '(399) Kirton Bank S.A. – Banco Múltiplo' },
  { id: '108', title: '(108) Portocred S.A.' },
  { id: '757', title: '(757) Banco Keb Hana Do Brasil S.A.' },
  { id: '102', title: '(102) XP Investimentos S.A.' },
  { id: '348', title: '(348) Banco XP S/A' },
  { id: '340', title: '(340) Super Pagamentos S/A (Superdital)' },
  { id: '084', title: '(084) Uniprime Norte Do Paraná' },
  { id: '180', title: '(180) Cm Capital Markets Cctvm Ltda' },
  { id: '066', title: '(066) Banco Morgan Stanley S.A.' },
  { id: '015', title: '(015) UBS Brasil Cctvm S.A.' },
  { id: '143', title: '(143) Treviso Cc S.A.' },
  { id: '062', title: '(062) Hipercard Banco Múltiplo S.A.' },
  { id: '074', title: '(074) Banco J. Safra S.A.' },
  { id: '099', title: '(099) Uniprime Central Ccc Ltda' },
  { id: '025', title: '(025) Banco Alfa S.A.' },
  { id: '075', title: '(075) Bco Abn Amro S.A.' },
  { id: '040', title: '(040) Banco Cargill S.A.' },
  { id: '190', title: '(190) Servicoop' },
  { id: '063', title: '(063) Banco Bradescard' },
  { id: '191', title: '(191) Nova Futura Ctvm Ltda' },
  { id: '064', title: '(064) Goldman Sachs Do Brasil Bm S.A.' },
  { id: '097', title: '(097) Ccc Noroeste Brasileiro Ltda' },
  { id: '016', title: '(016) Ccm Desp Trâns Sc E Rs' },
  { id: '012', title: '(012) Banco Inbursa' },
  { id: '003', title: '(003) Banco Da Amazônia S.A.' },
  { id: '060', title: '(060) Confidence Cc S.A.' },
  { id: '037', title: '(037) Banco Do Estado Do Pará S.A.' },
  { id: '159', title: '(159) Casa do Crédito S.A.' },
  { id: '172', title: '(172) Albatross Ccv S.A.' },
  { id: '085', title: '(085) Cooperativa Central de Créditos – Ailos' },
  { id: '114', title: '(114) Central Cooperativa De Crédito no Estado do Espírito Santo' },
  { id: '036', title: '(036) Banco Bradesco BBI S.A.' },
  { id: '394', title: '(394) Banco Bradesco Financiamentos S.A.' },
  { id: '004', title: '(004) Banco Do Nordeste Do Brasil S.A.' },
  { id: '320', title: '(320) China Construction Bank – Ccb Brasil S.A.' },
  { id: '189', title: '(189) Hs Financeira' },
  { id: '105', title: '(105) Lecca Cfi S.A.' },
  { id: '076', title: '(076) Banco KDB Brasil S.A.' },
  { id: '082', title: '(082) Banco Topázio S.A.' },
  { id: '286', title: '(286) Cooperativa de Crédito Rural de De Ouro' },
  { id: '093', title: '(093) PóloCred Scmepp Ltda' },
  { id: '273', title: '(273) Ccr De São Miguel Do Oeste' },
  { id: '157', title: '(157) Icap Do Brasil Ctvm Ltda' },
  { id: '183', title: '(183) Socred S.A.' },
  { id: '014', title: '(014) Natixis Brasil S.A.' },
  { id: '130', title: '(130) Caruana Scfi' },
  { id: '127', title: '(127) Codepe Cvc S.A.' },
  { id: '079', title: '(079) Banco Original Do Agronegócio S.A.' },
  { id: '081', title: '(081) Bbn Banco Brasileiro De Negocios S.A.' },
  { id: '118', title: '(118) Standard Chartered Bi S.A.' },
  { id: '133', title: '(133) Cresol Confederação' },
  { id: '121', title: '(121) Banco Agibank S.A.' },
  { id: '083', title: '(083) Banco Da China Brasil S.A.' },
  { id: '138', title: '(138) Get Money Cc Ltda' },
  { id: '024', title: '(024) Banco Bandepe S.A.' },
  { id: '095', title: '(095) Banco Confidence De Câmbio S.A.' },
  { id: '094', title: '(094) Banco Finaxis' },
  { id: '276', title: '(276) Senff S.A.' },
  { id: '137', title: '(137) Multimoney Cc Ltda' },
  { id: '092', title: '(092) BRK S.A.' },
  { id: '047', title: '(047) Banco do Estado de Sergipe S.A.' },
  { id: '144', title: '(144) Bexs Banco De Cambio S.A.' },
  { id: '126', title: '(126) BR Partners Banco de Investimento S.A.' },
  { id: '301', title: '(301) BPP Instituição De Pagamentos S.A.' },
  { id: '173', title: '(173) BRL Trust Dtvm Sa' },
  { id: '119', title: '(119) Banco Western Union do Brasil S.A.' },
  { id: '254', title: '(254) Paraná Banco S.A.' },
  { id: '268', title: '(268) Barigui Companhia Hipotecária' },
  { id: '107', title: '(107) Banco Bocom BBM S.A.' },
  { id: '412', title: '(412) Banco Capital S.A.' },
  { id: '124', title: '(124) Banco Woori Bank Do Brasil S.A.' },
  { id: '149', title: '(149) Facta S.A. Cfi' },
  { id: '197', title: '(197) Stone Pagamentos S.A.' },
  { id: '142', title: '(142) Broker Brasil Cc Ltda' },
  { id: '389', title: '(389) Banco Mercantil Do Brasil S.A.' },
  { id: '184', title: '(184) Banco Itaú BBA S.A.' },
  { id: '634', title: '(634) Banco Triangulo S.A (Banco Triângulo)' },
  { id: '545', title: '(545) Senso Ccvm S.A.' },
  { id: '132', title: '(132) ICBC do Brasil Bm S.A.' },
  { id: '298', title: '(298) Vip’s Cc Ltda' },
  { id: '129', title: '(129) UBS Brasil Bi S.A.' },
  { id: '128', title: '(128) Ms Bank S.A Banco De Câmbio' },
  { id: '194', title: '(194) Parmetal Dtvm Ltda' },
  { id: '310', title: '(310) VORTX Dtvm Ltda' },
  { id: '163', title: '(163) Commerzbank Brasil S.A Banco Múltiplo' },
  { id: '280', title: '(280) Avista S.A.' },
  { id: '146', title: '(146) Guitta Cc Ltda' },
  { id: '279', title: '(279) Ccr De Primavera Do Leste' },
  { id: '182', title: '(182) Dacasa Financeira S/A' },
  { id: '278', title: '(278) Genial Investimentos Cvm S.A.' },
  { id: '271', title: '(271) Ib Cctvm Ltda' },
  { id: '021', title: '(021) Banco Banestes S.A.' },
  { id: '246', title: '(246) Banco Abc Brasil S.A.' },
  { id: '751', title: '(751) Scotiabank Brasil' },
  { id: '208', title: '(208) Banco BTG Pactual S.A.' },
  { id: '746', title: '(746) Banco Modal S.A.' },
  { id: '241', title: '(241) Banco Classico S.A.' },
  { id: '612', title: '(612) Banco Guanabara S.A.' },
  { id: '604', title: '(604) Banco Industrial Do Brasil S.A.' },
  { id: '505', title: '(505) Banco Credit Suisse (Brl) S.A.' },
  { id: '196', title: '(196) Banco Fair Cc S.A.' },
  { id: '300', title: '(300) Banco La Nacion Argentina' },
  { id: '477', title: '(477) Citibank N.A.' },
  { id: '266', title: '(266) Banco Cedula S.A.' },
  { id: '122', title: '(122) Banco Bradesco BERJ S.A.' },
  { id: '376', title: '(376) Banco J.P. Morgan S.A.' },
  { id: '473', title: '(473) Banco Caixa Geral Brasil S.A.' },
  { id: '745', title: '(745) Banco Citibank S.A.' },
  { id: '120', title: '(120) Banco Rodobens S.A.' },
  { id: '265', title: '(265) Banco Fator S.A.' },
  { id: '007', title: '(007) BNDES (Banco Nacional Do Desenvolvimento Social)' },
  { id: '188', title: '(188) Ativa S.A Investimentos' },
  { id: '134', title: '(134) BGC Liquidez Dtvm Ltda' },
  { id: '641', title: '(641) Banco Alvorada S.A.' },
  { id: '029', title: '(029) Banco Itaú Consignado S.A.' },
  { id: '243', title: '(243) Banco Máxima S.A.' },
  { id: '078', title: '(078) Haitong Bi Do Brasil S.A.' },
  { id: '111', title: '(111) Banco Oliveira Trust Dtvm S.A.' },
  { id: '017', title: '(017) Bny Mellon Banco S.A.' },
  { id: '174', title: '(174) Pernambucanas Financ S.A.' },
  { id: '495', title: '(495) La Provincia Buenos Aires Banco' },
  { id: '125', title: '(125) Brasil Plural S.A Banco' },
  { id: '488', title: '(488) Jpmorgan Chase Bank' },
  { id: '065', title: '(065) Banco Andbank S.A.' },
  { id: '492', title: '(492) Ing Bank N.V.' },
  { id: '250', title: '(250) Banco Bcv' },
  { id: '145', title: '(145) Levycam Ccv Ltda' },
  { id: '494', title: '(494) Banco Rep Oriental Uruguay' },
  { id: '253', title: '(253) Bexs Cc S.A.' },
  { id: '269', title: '(269) Hsbc Banco De Investimento' },
  { id: '213', title: '(213) Bco Arbi S.A.' },
  { id: '139', title: '(139) Intesa Sanpaolo Brasil S.A.' },
  { id: '018', title: '(018) Banco Tricury S.A.' },
  { id: '630', title: '(630) Banco Intercap S.A.' },
  { id: '224', title: '(224) Banco Fibra S.A.' },
  { id: '600', title: '(600) Banco Luso Brasileiro S.A.' },
  { id: '623', title: '(623) Banco Pan S.A.' },
  { id: '204', title: '(204) Banco Bradesco Cartoes S.A.' },
  { id: '479', title: '(479) Banco ItauBank S.A.' },
  { id: '456', title: '(456) Banco MUFG Brasil S.A.' },
  { id: '464', title: '(464) Banco Sumitomo Mitsui Brasil S.A.' },
  { id: '613', title: '(613) Omni Banco S.A.' },
  { id: '652', title: '(652) Itaú Unibanco Holding Bm S.A.' },
  { id: '653', title: '(653) Banco Indusval S.A.' },
  { id: '069', title: '(069) Banco Crefisa S.A.' },
  { id: '370', title: '(370) Banco Mizuho S.A.' },
  { id: '249', title: '(249) Banco Investcred Unibanco S.A.' },
  { id: '318', title: '(318) Banco BMG S.A.' },
  { id: '626', title: '(626) Banco Ficsa S.A.' },
  { id: '270', title: '(270) Sagitur Cc Ltda' },
  { id: '366', title: '(366) Banco Societe Generale Brasil' },
  { id: '113', title: '(113) Magliano S.A.' },
  { id: '131', title: '(131) Tullett Prebon Brasil Cvc Ltda' },
  { id: '011', title: '(011) C.Suisse Hedging-Griffo Cv S.A (Credit Suisse)' },
  { id: '611', title: '(611) Banco Paulista' },
  { id: '755', title: '(755) Bofa Merrill Lynch Bm S.A.' },
  { id: '089', title: '(089) Ccr Reg Mogiana' },
  { id: '643', title: '(643) Banco Pine S.A.' },
  { id: '140', title: '(140) Easynvest – Título Cv S.A.' },
  { id: '707', title: '(707) Banco Daycoval S.A.' },
  { id: '288', title: '(288) Carol Dtvm Ltda' },
  { id: '101', title: '(101) Renascença Dtvm Ltda' },
  { id: '487', title: '(487) Deutsche Bank S.A (Banco Alemão)' },
  { id: '233', title: '(233) Banco Cifra S.A.' },
  { id: '177', title: '(177) Guide Investimentos S.A. Corretora de Valores' },
  { id: '633', title: '(633) Banco Rendimento S.A.' },
  { id: '218', title: '(218) Banco Bs2 S.A.' },
  { id: '292', title: '(292) BS2 Distribuidora De Títulos E Investimentos' },
  { id: '169', title: '(169) Banco Olé Bonsucesso Consignado S.A.' },
  { id: '293', title: '(293) Lastro Rdv Dtvm Ltda' },
  { id: '285', title: '(285) Frente Cc Ltda' },
  { id: '080', title: '(080) B&T Cc Ltda' },
  { id: '753', title: '(753) Novo Banco Continental S.A Bm' },
  { id: '222', title: '(222) Banco Crédit Agricole Br S.A.' },
  { id: '754', title: '(754) Banco Sistema S.A.' },
  { id: '098', title: '(098) Credialiança Ccr' },
  { id: '610', title: '(610) Banco VR S.A.' },
  { id: '712', title: '(712) Banco Ourinvest S.A.' },
  { id: '010', title: '(010) CREDICOAMO CRÉDITO RURAL COOPERATIVA' },
  { id: '283', title: '(283) RB Capital Investimentos Dtvm Ltda' },
  { id: '217', title: '(217) Banco John Deere S.A.' },
  { id: '117', title: '(117) Advanced Cc Ltda' },
  { id: '336', title: '(336) Banco C6 S.A – C6 Bank' },
  { id: '654', title: '(654) Banco A.J. Renner S.A.' },
  { id: '272', title: '(272) AGK Corretora de Câmbio S.A.' },
  { id: '330', title: '(330) Banco Bari de Investimentos e Financiamentos S.A.' },
  { id: '362', title: '(362) CIELO S.A.' },
  { id: '322', title: '(322) Cooperativa de Crédito Rural de Abelardo Luz – Sulcredi/Crediluz' },
  { id: '350', title: '(350) Cooperativa De Crédito Rural De Pequenos Agricultores E Da Reforma Agrária Do Ce' },
  { id: '091', title: '(091) Central De Cooperativas De Economia E Crédito Mútuo Do Estado Do Rio Grande Do S' },
  { id: '379', title: '(379) COOPERFORTE – Cooperativa De Economia E Crédito Mútuo Dos Funcionários De Instit' },
  { id: '378', title: '(378) BBC LEASING S.A. – Arrendamento Mercantil' },
  { id: '360', title: '(360) TRINUS Capital Distribuidora De Títulos E Valores Mobiliários S.A.' },
  { id: '084', title: '(084) UNIPRIME NORTE DO PARANÁ – COOPERATIVA DE CRÉDITO LTDA' },
  { id: '387', title: '(387) Banco Toyota do Brasil S.A.' },
  { id: '326', title: '(326) PARATI – CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.' },
  { id: '315', title: '(315) PI Distribuidora de Títulos e Valores Mobiliários S.A.' },
  { id: '307', title: '(307) Terra Investimentos Distribuidora de Títulos e Valores Mobiliários Ltda.' },
  { id: '296', title: '(296) VISION S.A. CORRETORA DE CAMBIO' },
  { id: '382', title: '(382) FIDÚCIA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE L' },
  { id: '097', title: '(097) Credisis – Central de Cooperativas de Crédito Ltda.' },
  { id: '016', title: '(016) COOPERATIVA DE CRÉDITO MÚTUO DOS DESPACHANTES DE TRÂNSITO DE SANTA CATARINA E RI' },
  { id: '299', title: '(299) SOROCRED   CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.' },
  { id: '359', title: '(359) ZEMA CRÉDITO, FINANCIAMENTO E INVESTIMENTO S/A' },
  { id: '391', title: '(391) COOPERATIVA DE CRÉDITO RURAL DE IBIAM – SULCREDI/IBIAM' },
  { id: '368', title: '(368) Banco CSF S.A.' },
  { id: '259', title: '(259) MONEYCORP BANCO DE CÂMBIO S.A.' },
  { id: '364', title: '(364) GERENCIANET S.A.' },
  { id: '014', title: '(014) STATE STREET BRASIL S.A. – BANCO COMERCIAL' },
  { id: '081', title: '(081) Banco Seguro S.A.' },
  { id: '384', title: '(384) GLOBAL FINANÇAS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO' },
  { id: '088', title: '(088) BANCO RANDON S.A.' },
  { id: '319', title: '(319) OM DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA' },
  { id: '274', title: '(274) MONEY PLUS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORT' },
  { id: '095', title: '(095) Travelex Banco de Câmbio S.A.' },
  { id: '332', title: '(332) Acesso Soluções de Pagamento S.A.' },
  { id: '325', title: '(325) Órama Distribuidora de Títulos e Valores Mobiliários S.A.' },
  { id: '331', title: '(331) Fram Capital Distribuidora de Títulos e Valores Mobiliários S.A.' },
  { id: '396', title: '(396) HUB PAGAMENTOS S.A.' },
  { id: '309', title: '(309) CAMBIONET CORRETORA DE CÂMBIO LTDA.' },
  { id: '313', title: '(313) AMAZÔNIA CORRETORA DE CÂMBIO LTDA.' },
  { id: '377', title: '(377) MS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LTDA' },
  { id: '321', title: '(321) CREFAZ SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORTE LT' },
  { id: '383', title: '(383) BOLETOBANCÁRIO.COM TECNOLOGIA DE PAGAMENTOS LTDA.' },
  { id: '324', title: '(324) CARTOS SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { id: '380', title: '(380) PICPAY SERVICOS S.A.' },
  { id: '343', title: '(343) FFA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LTDA.' },
  { id: '349', title: '(349) AL5 S.A. CRÉDITO, FINANCIAMENTO E INVESTIMENTO' },
  { id: '374', title: '(374) REALIZE CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.' },
  { id: '352', title: '(352) TORO CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA' },
  { id: '329', title: '(329) QI Sociedade de Crédito Direto S.A.' },
  { id: '342', title: '(342) Creditas Sociedade de Crédito Direto S.A.' },
  { id: '397', title: '(397) LISTO SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { id: '355', title: '(355) ÓTIMO SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { id: '367', title: '(367) VITREO DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.' },
  { id: '373', title: '(373) UP.P SOCIEDADE DE EMPRÉSTIMO ENTRE PESSOAS S.A.' },
  { id: '408', title: '(408) BÔNUSCRED SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { id: '404', title: '(404) SUMUP SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { id: '403', title: '(403) CORA SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { id: '306', title: '(306) PORTOPAR DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.' },
  { id: '174', title: '(174) PEFISA S.A. – CRÉDITO, FINANCIAMENTO E INVESTIMENTO' },
  { id: '354', title: '(354) NECTON INVESTIMENTOS S.A. CORRETORA DE VALORES MOBILIÁRIOS E COMMODITIES' },
  { id: '630', title: '(630) Banco Smartbank S.A.' },
  { id: '393', title: '(393) Banco Volkswagen S.A.' },
  { id: '390', title: '(390) BANCO GM S.A.' },
  { id: '381', title: '(381) BANCO MERCEDES-BENZ DO BRASIL S.A.' },
  { id: '626', title: '(626) BANCO C6 CONSIGNADO S.A.' },
  { id: '755', title: '(755) Bank of America Merrill Lynch Banco Múltiplo S.A.' },
  { id: '089', title: '(089) CREDISAN COOPERATIVA DE CRÉDITO' },
  { id: '363', title: '(363) SOCOPA SOCIEDADE CORRETORA PAULISTA S.A.' },
  { id: '365', title: '(365) SOLIDUS S.A. CORRETORA DE CAMBIO E VALORES MOBILIARIOS' },
  { id: '281', title: '(281) Cooperativa de Crédito Rural Coopavel' },
  { id: '654', title: '(654) BANCO DIGIMAIS S.A.' },
  { id: '371', title: '(371) WARREN CORRETORA DE VALORES MOBILIÁRIOS E CÂMBIO LTDA.' },
  { id: '289', title: '(289) DECYSEO CORRETORA DE CAMBIO LTDA.' },
];
